import type { CorridorProfile } from "./types";

export const sampleCorridorProfile: CorridorProfile = {
  id: "corridor-demo-cobalt-001",
  name: "Synthetic Critical Minerals Corridor",
  commodity: "Cobalt",
  geography: "Demonstration geography",
  status: "synthetic-demo",
  summary:
    "A synthetic, non-operational corridor profile showing how EEO connects endowment, governance, value-chain, labor, ecological, and public-benefit questions to evidence metadata.",
  limits: [
    "This prototype uses synthetic/sample data only.",
    "No legal finding is made.",
    "Reported trade data would provide context only; it would not prove physical chain-of-custody.",
    "Spatial proximity would be treated as a risk signal, not causation evidence.",
    "Sensitive data would be aggregated, restricted, community-governed, or suppressed.",
  ],
  steps: [
    {
      id: "step-endowment",
      label: "Endowment",
      description: "Documents resource context without asserting ownership or entitlement.",
      evidenceClaimIds: ["CLAIM-DEMO-001"],
      disclosureTier: "contextual public",
    },
    {
      id: "step-governance",
      label: "Governance",
      description: "Connects laws, concessions, contracts, agencies, and review status to evidence.",
      evidenceClaimIds: ["CLAIM-DEMO-002"],
      disclosureTier: "contextual public",
    },
    {
      id: "step-value-chain",
      label: "Value Chain",
      description: "Shows extraction, processing, export, and trade-context questions without traceability overclaims.",
      evidenceClaimIds: ["CLAIM-DEMO-003"],
      disclosureTier: "aggregated",
    },
    {
      id: "step-public-benefit",
      label: "Public Benefit Question",
      description: "Frames revenue as a question requiring evidence, not proof of durable public benefit.",
      evidenceClaimIds: ["CLAIM-DEMO-004"],
      disclosureTier: "contextual public",
    },
  ],
  claims: [
    {
      id: "CLAIM-DEMO-001",
      claimText: "This demonstration corridor contains a synthetic endowment profile used only to test EEO's evidence and disclosure workflow.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "factual",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "open",
      sourceTitle: "EEO synthetic sample dataset",
      sourceLocator: "internal-demo://eeo/sample-corridor",
      sourceDate: "2026-05-31",
      retrievalDate: "2026-05-31",
      licenseOrUseBasis: "Internal synthetic demonstration data",
      method: "Synthetic sample generated for product testing.",
      confidenceExplanation: "Confidence is limited to the sample-data context; it does not describe a real site, company, or jurisdiction.",
      staleAfter: "2026-08-31",
      reviewStatus: "reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-002",
      claimText: "A real EEO governance profile would connect public records to concessions, authorities, review status, and correction paths.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "contextual public",
      sourceTitle: "EEO implementation framework",
      sourceLocator: "internal-doc://eeo/framework",
      sourceDate: "2026-05-31",
      retrievalDate: "2026-05-31",
      licenseOrUseBasis: "Internal project documentation",
      method: "Derived from EEO MVP design requirements.",
      confidenceExplanation: "This is a product-method claim about intended workflow, not a real-world factual claim.",
      staleAfter: "2026-08-31",
      reviewStatus: "reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-003",
      claimText: "Reported trade data, if used in a real corridor, would be treated as context and would not prove physical chain-of-custody.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "aggregated",
      sourceTitle: "EEO language guardrail",
      sourceLocator: "internal-doc://eeo/language-guardrails",
      sourceDate: "2026-05-31",
      retrievalDate: "2026-05-31",
      licenseOrUseBasis: "Internal project documentation",
      method: "Canonical language constraint.",
      confidenceExplanation: "This is a canonical limitation statement for safe public interpretation.",
      staleAfter: "2026-08-31",
      reviewStatus: "exposure-reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-004",
      claimText: "Public revenue disclosure raises a public-benefit question; it does not by itself prove durable public benefit.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "contextual public",
      sourceTitle: "EEO evidence discipline rule",
      sourceLocator: "internal-doc://eeo/evidence-claim-schema",
      sourceDate: "2026-05-31",
      retrievalDate: "2026-05-31",
      licenseOrUseBasis: "Internal project documentation",
      method: "Canonical limitation statement.",
      confidenceExplanation: "This is a safe interpretation rule, not a factual claim about a real revenue flow.",
      staleAfter: "2026-08-31",
      reviewStatus: "reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
  ],
};
