import type { CorridorProfile } from "./types";

export const sampleCorridorProfile: CorridorProfile = {
  id: "corridor-demo-cobalt-001",
  name: "Synthetic Cobalt Endowment-to-Economy Corridor",
  commodity: "Cobalt",
  geography: "Demonstration geography",
  status: "synthetic-demo",
  summary:
    "A synthetic, non-operational corridor profile showing how EEO connects one commodity, one geography, and one complete endowment-to-economy chain across governance, ownership, labor, trade, ecology, public revenue, and value capture questions.",
  limits: [
    "This prototype uses synthetic/sample data only.",
    "No legal finding is made.",
    "This is a federated public-interest observatory pattern, not a global resource registry.",
    "Reported trade data would provide context only; it would not prove physical chain-of-custody.",
    "Spatial proximity would be treated as a risk signal, not causation evidence.",
    "Sensitive data would be aggregated, restricted, community-governed, or suppressed.",
    "Indigenous data governance, sovereignty respect, exposure ethics, and right-of-reply review are release gates, not optional editorial notes.",
  ],
  steps: [
    {
      id: "step-endowment",
      label: "Endowment",
      description: "Documents resource context without asserting ownership or entitlement.",
      evidenceClaimIds: ["CLAIM-DEMO-001"],
      disclosureTier: "contextual public",
    },
    {
      id: "step-governance-ownership",
      label: "Governance and Ownership",
      description: "Connects laws, concessions, contracts, authorities, beneficial-control questions, and review status to evidence.",
      evidenceClaimIds: ["CLAIM-DEMO-002", "CLAIM-DEMO-005"],
      disclosureTier: "contextual public",
    },
    {
      id: "step-labor-ecology",
      label: "Labor and Ecology",
      description: "Frames worker, community, and ecological risk signals without converting proximity or third-party reporting into findings.",
      evidenceClaimIds: ["CLAIM-DEMO-006"],
      disclosureTier: "community-governed",
    },
    {
      id: "step-trade",
      label: "Trade Context",
      description: "Shows processing, export, and trade-context questions without traceability overclaims.",
      evidenceClaimIds: ["CLAIM-DEMO-003"],
      disclosureTier: "aggregated",
    },
    {
      id: "step-public-revenue-value-capture",
      label: "Public Revenue and Value Capture",
      description: "Asks who benefits, who bears risk, and what public value can be evidenced without treating revenue disclosure as proof of durable public benefit.",
      evidenceClaimIds: ["CLAIM-DEMO-004", "CLAIM-DEMO-007"],
      disclosureTier: "contextual public",
    },
  ],
  reasoningDimensions: [
    {
      id: "dimension-endowments",
      label: "Endowments",
      question: "What natural endowment is in scope, at what public-safe granularity, and with what uncertainty?",
      evidenceClaimIds: ["CLAIM-DEMO-001"],
      disclosureTier: "contextual public",
    },
    {
      id: "dimension-governance",
      label: "Governance",
      question: "Which public authorities, legal instruments, stewardship duties, and review gates shape the corridor?",
      evidenceClaimIds: ["CLAIM-DEMO-002"],
      disclosureTier: "contextual public",
    },
    {
      id: "dimension-ownership",
      label: "Ownership",
      question: "What ownership or control questions can be described from public records without implying legal findings?",
      evidenceClaimIds: ["CLAIM-DEMO-005"],
      disclosureTier: "contextual public",
    },
    {
      id: "dimension-labor",
      label: "Labor",
      question: "What worker and community risk signals require careful sourcing, right-of-reply, and harm-aware disclosure?",
      evidenceClaimIds: ["CLAIM-DEMO-006"],
      disclosureTier: "community-governed",
    },
    {
      id: "dimension-trade",
      label: "Trade",
      question: "What reported flows provide trade context while avoiding physical chain-of-custody claims?",
      evidenceClaimIds: ["CLAIM-DEMO-003"],
      disclosureTier: "aggregated",
    },
    {
      id: "dimension-ecology",
      label: "Ecology",
      question: "Which ecological risk signals are safe to show publicly, and which require aggregation or suppression?",
      evidenceClaimIds: ["CLAIM-DEMO-006"],
      disclosureTier: "community-governed",
    },
    {
      id: "dimension-public-revenue",
      label: "Public Revenue",
      question: "What public revenue is reported, and what remains unknown about durable public benefit?",
      evidenceClaimIds: ["CLAIM-DEMO-004"],
      disclosureTier: "contextual public",
    },
    {
      id: "dimension-value-capture",
      label: "Value Capture",
      question: "Where might value accrue across the corridor, and what evidence is needed before any public conclusion is drawn?",
      evidenceClaimIds: ["CLAIM-DEMO-007"],
      disclosureTier: "contextual public",
    },
  ],
  claims: [
    {
      id: "CLAIM-DEMO-001",
      claimText: "This demonstration corridor contains a synthetic endowment profile used only to test EEO's evidence and disclosure workflow.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "factual",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "open",
      sourceTitle: "EEO synthetic sample dataset",
      sourceLocator: "internal-demo://eeo/sample-corridor",
      sourceDate: "2026-05-31",
      retrievalDate: "2026-05-31",
      licenseOrUseBasis: "Internal synthetic demonstration data",
      method: "Synthetic sample generated for product testing.",
      confidenceExplanation: "Confidence is limited to the sample-data context; it does not describe a real site, company, or jurisdiction.",
      staleAfter: "2026-08-31",
      reviewStatus: "reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-002",
      claimText: "A real EEO governance profile would connect public records to concessions, authorities, review status, and correction paths.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "contextual public",
      sourceTitle: "EEO implementation framework",
      sourceLocator: "internal-doc://eeo/framework",
      sourceDate: "2026-05-31",
      retrievalDate: "2026-05-31",
      licenseOrUseBasis: "Internal project documentation",
      method: "Derived from EEO MVP design requirements.",
      confidenceExplanation: "This is a product-method claim about intended workflow, not a real-world factual claim.",
      staleAfter: "2026-08-31",
      reviewStatus: "reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-003",
      claimText: "Reported trade data, if used in a real corridor, would be treated as context and would not prove physical chain-of-custody.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "aggregated",
      sourceTitle: "EEO language guardrail",
      sourceLocator: "internal-doc://eeo/language-guardrails",
      sourceDate: "2026-05-31",
      retrievalDate: "2026-05-31",
      licenseOrUseBasis: "Internal project documentation",
      method: "Canonical language constraint.",
      confidenceExplanation: "This is a canonical limitation statement for safe public interpretation.",
      staleAfter: "2026-08-31",
      reviewStatus: "exposure-reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-004",
      claimText: "Public revenue disclosure raises a public-benefit question; it does not by itself prove durable public benefit.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "contextual public",
      sourceTitle: "EEO evidence discipline rule",
      sourceLocator: "internal-doc://eeo/evidence-claim-schema",
      sourceDate: "2026-05-31",
      retrievalDate: "2026-05-31",
      licenseOrUseBasis: "Internal project documentation",
      method: "Canonical limitation statement.",
      confidenceExplanation: "This is a safe interpretation rule, not a factual claim about a real revenue flow.",
      staleAfter: "2026-08-31",
      reviewStatus: "reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-005",
      claimText: "Ownership and control questions in EEO require public-record sourcing, jurisdiction-specific context, and legal-posture labels before publication.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "contextual public",
      sourceTitle: "EEO governance and ownership guardrail",
      sourceLocator: "internal-doc://eeo/governance-ownership-guardrail",
      sourceDate: "2026-06-02",
      retrievalDate: "2026-06-02",
      licenseOrUseBasis: "Internal project documentation",
      method: "Canonical limitation statement for ownership/control reasoning.",
      confidenceExplanation: "This is a product-method claim about evidence handling, not a factual claim about a real owner or controller.",
      staleAfter: "2026-09-02",
      reviewStatus: "reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-006",
      claimText: "Labor, community, and ecological risk signals may require aggregation, community-governed handling, or suppression before public release.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "community-governed",
      sourceTitle: "EEO exposure ethics guardrail",
      sourceLocator: "internal-doc://eeo/exposure-ethics-guardrail",
      sourceDate: "2026-06-02",
      retrievalDate: "2026-06-02",
      licenseOrUseBasis: "Internal project documentation",
      method: "Disclosure-risk rule for sensitive labor, community, and ecological contexts.",
      confidenceExplanation: "This is a governance safeguard claim and does not describe a real community, worker group, or ecological site.",
      staleAfter: "2026-09-02",
      reviewStatus: "exposure-reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
    {
      id: "CLAIM-DEMO-007",
      claimText: "Value capture analysis in EEO connects benefit, risk, and evidence gaps without ranking actors or making certification claims.",
      claimType: "modeled",
      confidenceLabel: "modeled",
      evidenceLayer: "analytical",
      granularity: "corridor-level",
      legalPosture: "no legal claim",
      disclosureTier: "contextual public",
      sourceTitle: "EEO value-capture reasoning guardrail",
      sourceLocator: "internal-doc://eeo/value-capture-reasoning-guardrail",
      sourceDate: "2026-06-02",
      retrievalDate: "2026-06-02",
      licenseOrUseBasis: "Internal project documentation",
      method: "Canonical limitation statement for benefit and value-capture analysis.",
      confidenceExplanation: "This is a product-method claim; it does not make a factual claim about any real actor's benefit or liability.",
      staleAfter: "2026-09-02",
      reviewStatus: "reviewed",
      correctionPath: "/eeo/corrections",
      rightOfReplyStatus: "not required",
    },
  ],
};
